# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9669fd5396273da702d643eab9b3859e8b3fd6c78f57e4ed5ea529257b7e994c8e3bb3b696c3c139c79564285b545a1bd1d607681bef5824022c70415756304c

test:
  secret_key_base: eede37737a682145a3f798665db1dad257bc30e0ebb41760241d79636f92a5c270ce590b213797440491da1bd9a214b6445ab9440d3e244f774d3ebe43b70734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
